"""deletando coluna source

Revision ID: 28720ed4ad34
Revises: 71a24060a834
Create Date: 2022-03-03 14:55:31.696000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28720ed4ad34'
down_revision = '71a24060a834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
