"""criado coluna source como inteiro

Revision ID: ce98dcc5aa06
Revises: 28720ed4ad34
Create Date: 2022-03-03 14:58:01.604514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce98dcc5aa06'
down_revision = '28720ed4ad34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('source', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'source')
    # ### end Alembic commands ###
